### ISSUE TITLE
Bookmarks?

### ISSUE THREAD

**Issue by georgedpeterson** [izderadicka/audioserve-android#16]
Hi, sorry, I couldn't find a better way to ask. I feel crazy, but how do I add a bookmark? Thanks for a great app!

**Comment by izderadicka** [comment]
shift file/folder item in list to left - two buttons appear - one for bookmark, other for download

**Comment by georgedpeterson** [comment]
Ah! Got it. Is there a doc somewhere I should have found that? Thanks! Love this.
