### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by flittermice** [izderadicka/audioserve-android#17]
I got audioserve running behind a reverse proxy and can use the web client without any problems. Judging after the browser, the certificate chain (it's a LetsEncrypt certificate) seems to be intact. 
In the Android app on my mobile device (Huawei T5 tablet) I entered URL and credentials. But when I do "Test Connection" I only get a brief popup "Connection error: Network".

`adb logcat ApiClient:D *:S` says:
```
11-25 10:43:50.353  4006  4006 D ApiClient: Client base URL is https://rsg.changeip.net/audioserve/
11-25 10:43:50.398  4006  4006 E ApiClient: Login error: com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```
Surely I can provide more logs if this is necessary.

I have already installed the "Let’s Encrypt Authority X3", but this didn't help.
Thanks very much for your help.

**Comment by izderadicka** [comment]
Application  is using android libraries, there is nothing specific in it.   So problem must be in android

**Comment by izderadicka** [comment]
I'm using let's encrypt myself in reverse proxy (nginx) and did not have problems.   Looks like root certificate is missing in your case. Installing root certificate in android can be tricky - first I'd try system upgrade.    Certificate must be installed system wide (so each application is seeing it I think location is /system/etc/security/cacerts/  - I was playing with certificates once, when I was [using mitproxy for android](http://zderadicka.eu/intercept-https-communication-from-an-android-application/)), which I believe can be done easily only on rooted  phone, but not sure about unrooted.

**Comment by flittermice** [comment]
Thanks for your elaborate answer, Ivan. I'll give it a try and report here in case I'm successful!

**Comment by flittermice** [comment]
It indeed seems to be a Let's Encrypt/Android specific problem. It works with both
- plain HTTP and
- HTTPS reverse proxy from another domain.
