### ISSUE TITLE
Can't get remote position: timeout

### ISSUE THREAD

**Issue by TheNomad11** [izderadicka/audioserve-android#18]
Exciting project, am trying to make it work a few hours already. Now I am close. Only thing I have trouble is syncing of playing position. I set group and secret, but cannot get android and laptop using the webinterface to sync. Android app says: Can't get remote position: timeout

 I run it like this:

docker run -d --name audioserve -p 3000:3000 -e AUDIOSERVE_SHARED_SECRET=12345 -v /home/myusername/audiobooks:/audiobooks  izderadicka/audioserve  /audiobooks

Thanks!

**Comment by izderadicka** [comment]
Is audioserve connected through reverse proxy? if yes assure that websockets are properly configure for reverse proxy endpoint for websocket.
For instance this is what I'm using for nginx:
```
location /audioserve/position {
      proxy_pass http://localhost:3000/position;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 3600s;
        }
```
You can also check that  websocket works in web browser. - In FF go to Web Developer / Network - reload audioserve page -  and you should see connected websocket like this:
![image](https://user-images.githubusercontent.com/2185733/102594629-b9f72580-4116-11eb-9c6b-d480c41efaf0.png)

Also you can test between two web clients ( in private mode or two browsers - not to share coockies and local storage) to see if it works and problem is then related only to android client.

**Comment by TheNomad11** [comment]
Thanks for your reply. I use apache. It seems my reverse-proxy set up is too basic. I am new to reverse-proxy and was not able to find a apache reverse proxy set-up, so I only used this:


```
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName servername.com
    AllowEncodedSlashes On
    ProxyPreserveHost On
    ProxyPass "/"  "http://localhost:3000/"

SSLCertificateFile /etc/letsencrypt/live.....
SSLCertificateKeyFile /etc/letsencrypt/live.....
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>


</IfModule>
```

Could you tell me how I can correctly add the location part in apache? Thanks! This could be added to the readme as well, then


EDIT: As expected, websocket does not seem to work. Status says 400

**Comment by TheNomad11** [comment]
Yeah, I've made it work, websockets are working and I was able to continue on the web interface where I left on the mobile app. In case there are other noobs struggling to get away from Google and others, it was quite easy, just add:

```
<Location "/position">
      ProxyPass "ws://localhost:3000/position"
  </Location>
```

**Comment by TheNomad11** [comment]
Maybe you can add it to the readme as there is no information available about how to configure apache reverse proxy

**Comment by izderadicka** [comment]
In audioserve repo there is now documents docs/reverse_proxy.md  (and I merged now to master some changes in readme about reverse proxy I've made some time ago).  If you want you can add your working apache configuration to that file as PR.

**Comment by TheNomad11** [comment]
Alright. Tried to create my first PR but it was not possible, was just greyed out, not so intuitive for a noob. Anyway, great project, will recommend it to anyone and I hope you will continue developing it!

**Comment by izderadicka** [comment]
PR is this case should not be  difficult - go to main project  https://github.com/izderadicka/audioserve  - Fork (top right btn),  in forked repo go to docs/reverse_proxy.md,   edit (you can easily edit in browser), Commit. Then you should have Pull Request link (in Code tab), click, check and Create Pull Request.

**Comment by TheNomad11** [comment]
Thanks for the explanation! I just created a pull request. Please double-check everything, I am no developer.
