### ISSUE TITLE
No player available/connection issues

### ISSUE THREAD

**Issue by crogers2287** [izderadicka/audioserve-android#2]
Hello,

When I try and connect to the server it shows "Connection error:Server" in the toast message at the bottom, but I can still see all of the files in my library. When I try and play a book, I get an error saying "Player not ready - probably not connected to server"

Here is a link to the screenshots:

http://imgur.com/a/NwlF5WU

Everything works from a browser with audioserve, only having connection issues in the app.

**Comment by izderadicka** [comment]
What is exact version of your Android?
Will you be able to get logcat of the app - https://developer.android.com/studio/command-line/logcat  (or can use logcat viewer in Android studio)?

**Comment by crogers2287** [comment]
[logcat.txt](https://github.com/izderadicka/audioserve-android/files/2948399/logcat.txt)

Phone verison info: http://imgur.com/a/GbxMdOg

**Comment by izderadicka** [comment]
Thanks,
here is relevant version of the log
```
03-09 08:15:36.813 23130 23130 E icka.audioserv: Not starting debugger since process cannot load the jdwp agent.
03-09 08:15:37.050 23130 23130 E ApiClient: Login error: com.android.volley.ClientError
03-09 08:15:42.574 23130 23130 E ApiClient: Login error: com.android.volley.ClientError
03-09 08:15:43.960 23130 23130 E ApiClient: Login error: com.android.volley.ClientError
03-09 08:15:57.904 23130 23130 E ApiClient: Network Error com.android.volley.TimeoutError
03-09 08:15:57.904 23130 23130 E audioserve-service: Api returned error: Network
03-09 08:15:57.905 23130 23130 E FolderFragment: Error loading folder folder/Brandon Sanderson/Oathbringer
03-09 08:16:11.861 23130 23130 E audioserve-service: Invalid state - Api client is not initialized
03-09 08:16:11.861 23130 23130 E audioserve-service: Folder is not synched or offline- cannot played
03-09 08:16:22.837 23130 23130 E audioserve-service: Invalid state - Api client is not initialized
03-09 08:16:22.837 23130 23130 E audioserve-service: Folder is not synched or offline- cannot played
```
No exact idea what is wrong,  clearly login failed, but not sure why - later the is network timeout - like if app cannot reach the server.  
Try to use audioserve from device web browser, if you have not done so already.  Also you can try app with my demo audioserve instance https://audioserve.herokuapp.com/   secret is mypass  - use it first from browser,  to be sure  server is started.

If above will work then you can try emulator against you server if there would be some issue.  Or problem might be with SSL/TLS - recent android forbids apps to connect with unencrypted connection, unless it's specified in app manifest, which is `android:usesCleartextTraffic="true"` and it is in this app manifest , but maybe it can be somehow everruled by phone OS. I'm testing on emulated Android 9, where it works fine.

**Comment by crogers2287** [comment]
Putting it behind a reverse proxy with SSL seems to have fixed the issue. Thanks for the help.

**Comment by izderadicka** [comment]
So probably related to particular platform? Not sure why plain communication was not working, as I cannot simulate such problems  neither in emulator nor on my phone.

**Comment by Ludo444** [comment]
just a note, this happened to me when running docker container with `--no-authentication` param, with secret set it works fine

**Comment by izderadicka** [comment]
@Ludo444 that is expected behaviour as android client expects server to support authentication with shared secret. `--no-authentication` is only for dev, when you playing with server.
