### ISSUE TITLE
Readme Information

### ISSUE THREAD

**Issue by NoahSchmitz** [izderadicka/audioserve-android#22]
Not sure if this is the right place to put this but I don't think this info in the Readme is correct:

"Too big files (like m4b file containing whole audiobook) will be hard to navigate (as internal chapters are not supported), slow to transcode, plus there is hard limit of 250MB per file (for security reasons)."

M4b's seem to work fine, including files with internal chapters, and I've tested files over 400MB without problem. I'm not complaining, as many of my books are in this format, but I'm wondering why the Readme says this.

**Comment by izderadicka** [comment]
Thanks for noting, this is legacy comment, before updating audioserve to support m4b and chapterised audio files. It should be updated.

**Comment by izderadicka** [comment]
update readme
