### ISSUE TITLE
"Connection error: Server" when testing connection on audioserve-android

### ISSUE THREAD

**Issue by xtay573269555** [izderadicka/audioserve-android#32]
Hi, i deployed the `audioserve` server on my local LAN, and it works well via browser except `audioserve-android` client. Here is the details of information i collected.

Screenshot of "Connection error: Server" raised by `audioserve-android` on clicking "Test Connection" :
<img width="178" alt="2024-02-08_10-19-37" src="https://github.com/izderadicka/audioserve-android/assets/5844466/38c4a404-c62e-4241-872c-6f05175030a9">

Screenshot of "Empty folder" raised by `audioserve-android` on tapping back from `Settings` :
<img width="177" alt="2024-02-08_10-20-41" src="https://github.com/izderadicka/audioserve-android/assets/5844466/cae48321-d6ae-4f3a-81e9-baf7afdc5be9">

Screenshot of collections on tapping `Browse Collections` in `audioserve-android`:
It seems like that the audioserve-android had fetched collections information successfully already.
<img width="164" alt="2024-02-08_10-21-24" src="https://github.com/izderadicka/audioserve-android/assets/5844466/b85edadf-0eb4-4305-890f-7bd0c53a3db9">

Screenshot of Firefox on android:
<img width="163" alt="2024-02-08_10-20-16" src="https://github.com/izderadicka/audioserve-android/assets/5844466/7074712c-d50c-4ad2-8b0c-261ae9f92426">

audioserve deployment info:
```
mkdir -p audioserve
mkdir -p /data/audio_dir_1
mkdir -p /data/audio_dir_2
chown -R share:share audioserve
chown -R share:share /data/audio_dir_1
chown -R share:share /data/audio_dir_2

cat <<EOF > audioserve/config.yaml
transcoding:
  low:
    opus-in-ogg:
      bitrate: 16
      compression_level: 3
      cutoff: WideBand
      mono: true
  medium:
    opus-in-ogg:
      bitrate: 24
      compression_level: 6
      cutoff: SuperWideBand
      mono: true
  high:
    opus-in-ogg:
      bitrate: 32
      compression_level: 9
      cutoff: SuperWideBand
EOF

chown -R share:share audioserve

docker run -d --restart unless-stopped \
  --name audioserve \
  -e PUID=1000 \
  -e PGID=1000 \
  -p 7777:3000 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /data/audio_dir_1:/library_1:ro \
  -v /data/audio_dir_2:/library_2:ro \
  -v "$PWD"/audioserve:/home/audioserve/.audioserve \
  -e AUDIOSERVE_LISTEN=0.0.0.0:3000 \
  -e AUDIOSERVE_NO_AUTHENTICATION=true \
  -e AUDIOSERVE_CONFIG=/home/audioserve/.audioserve/config.yaml \
  -e AUDIOSERVE_ALLOW_SYMLINKS=true \
  -e AUDIOSERVE_T_CACHE_DIR=/tmp \
  -e AUDIOSERVE_NO_NATURAL_FILES_ORDERING=true \
  -e AUDIOSERVE_CHANGES_DEBOUNCE_INTERVAL=10 \
  -e AUDIOSERVE_TAGS=true \
  -e AUDIOSERVE_BEHIND_PROXY=false \
  -e AUDIOSERVE_TRANSCODING_MAX_PARALLEL_PROCESSES=8 \
  -e AUDIOSERVE_POSITIONS_BACKUP_SCHEDULE="0 3 * * *" \
  -e AUDIOSERVE_POSITIONS_BACKUP_FILE=/home/audioserve/.audioserve/positions-backup.json \
  -e AUDIOSERVE_DEBUG=true \
  izderadicka/audioserve:v0.26.2 \
  /library_1 /library_2
```

**Comment by xtay573269555** [comment]
docker logs of `audioserve `:
```
[root@docker docker_data]# docker logs -f audioserve 
[2024-02-08T02:11:34Z INFO  audioserve] Started audioserve 0.26.2 #68ecd16 with features async-tar, async-zip, behind-proxy, chrono, cron, default, folder-download, futures-util, proxy-headers, rustls-pemfile, shared-positions, symlinks, tls, tokio-rustls, websock
[2024-02-08T02:11:34Z WARN  collection::cache] Cannot read previous folder options on "/library_1" due to No such file or directory (os error 2), will enforce full cache update
[2024-02-08T02:11:34Z WARN  collection::cache] Cannot read previous folder options on "/library_2" due to No such file or directory (os error 2), will enforce full cache update
[2024-02-08T02:11:34Z INFO  audioserve] Server listening on 0.0.0.0:3000
[2024-02-08T02:11:34Z INFO  collection::cache] Full scan for collection "/library_2" finished
[2024-02-08T02:11:34Z INFO  collection::cache] Full scan for collection "/library_1" finished
```

My phone info:
```
vendor: Google
model: Pixel 4a
os: Android 13
```

**Comment by izderadicka** [comment]
Hi,
I think problem might be with this option of audioserve:

`-e AUDIOSERVE_NO_AUTHENTICATION=true`

This is for testing purposes only and if I remember correctly it was not implemented in android client - try with some shared secret.


FYI: the android client is legacy now, not maintained, preferred now is web PWA client.

**Comment by xtay573269555** [comment]
Thanks for reply. I am using web client now.

One more information for others who are facing the same problem.

It doesn't work after removing `-e AUDIOSERVE_NO_AUTHENTICATION=true` and adding the following options.

```
  -e AUDIOSERVE_NO_AUTHENTICATION=false \
  -e AUDIOSERVE_SHARED_SECRET=123456 \
  -e AUDIOSERVE_SSL_CERT=/home/audioserve/.audioserve/server.crt \
  -e AUDIOSERVE_SSL_KEY=/home/audioserve/.audioserve/server.key \
```

**Comment by izderadicka** [comment]
Thanks for update, if you're using custom TLS certificates there might be
problem with certificate chain trust on Android?
