### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by jakob42** [izderadicka/audioserve-android#4]
Hi,

any chance I might interest you in implementing a dark mode? I usually use it in bed on my amoled screen and the white background is way too bright for me.

Thanks for the app!

**Comment by izderadicka** [comment]
Agree, that would be nice.  I'm not very efficient in Android styling, so I'm happy to put together this UI. I guess it'll require a bit of refactoring of UI styles. If anyone if proficient in this area **help is more then welcomed**,  I'm not very good at that ( and frankly spoken not very much fond of working on UIs).

**Comment by jakob42** [comment]
Thanks for considering! I hate design as well

**Comment by izderadicka** [comment]
Some work has been done - in #15 -  now is separate branch - it's dark (based on system setting), but still few things missing. But I started to test it on my mobile. If somebody else wants to try (but you'll need to build from that branch).

**Comment by izderadicka** [comment]
Dark (Night) mode is now available in v.0.8.6   - it was bit tedious for me to set styles right (especially notifications are tricky), but it is dark and looks okish.
