### ISSUE TITLE
Variable bitrate and position seeker

### ISSUE THREAD

**Issue by zais** [izderadicka/audioserve-android#8]
Looks like position seeker goes wild in case of variable bitrate encoded audio files.
Example: pause close to end of such file will cause play to jump way back

Not sure how current position is storred, probably as time, may be should be byte offset.

**Comment by izderadicka** [comment]
We are using [Exoplayer ](https://github.com/google/ExoPlayer)and AFAIK only seeking by time is possible there. As exoplayer is responsible for all playback and seeking I guess problem is there - it would worth to check with other apps that are using exoplayer or with some raw exoplayer example.

**Comment by zais** [comment]
Exoplayer has many issues with that, as i can see (example: https://github.com/google/ExoPlayer/issues/6698). Ok, will suffer through such files ;).

**Comment by izderadicka** [comment]
or enforce transcoding
